- id: '1711412922995'
  alias: Couch an
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 74a8418a735465796401d2bd7716f086
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.couch
  mode: single
- id: '1711413027657'
  alias: Couch aus
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 0dbffd293dd7591b9de64be93e01a9eb
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.couch
  mode: single
- id: '1711413112673'
  alias: Esstisch an
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 14cd00ec73898d8d70c5ee0d583df262
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.esstisch
  mode: single
- id: '1711413130920'
  alias: Esstisch aus
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 7dbd6355ef1837d2cd7ce0895f90cbc4
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.esstisch
  mode: single
- id: '1711624301117'
  alias: Away Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.musti_s_iphone
    from: home
    to: not_home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are not Home anymore
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.couch
      - light.eingang
      - light.esstisch
      - light.schlafzimmer_lampe
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.desk_switch_0
  mode: single
- id: '1711624343409'
  alias: Home Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.musti_s_iphone
    from: not_home
    to: home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are back Home
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.eingang
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.couch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.eingang
  mode: single
