- id: '1711624301117'
  alias: Away Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.musti_s_iphone
    from: home
    to: not_home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are not Home anymore
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.couch
      - light.eingang
      - light.esstisch
      - light.schlafzimmer_lampe
  - service: switch.turn_off
    metadata: {}
    data: {}
    target:
      device_id: ce391c61d887f8b94aaef49fd50c8d26
  - service: scene.turn_on
    metadata: {}
    target:
      entity_id: scene.led_off
  mode: single
- id: '1711624343409'
  alias: Home Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.musti_s_iphone
    from: not_home
    to: home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are back Home
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.eingang
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.couch
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: light.eingang
  mode: single
- id: '1712587000202'
  alias: Wasser erkannt
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.flood_badezimmer_flood
    - binary_sensor.flood_kuche_flood
    to: 'on'
  action:
  - service: notify.notify
    metadata: {}
    data:
      title: ALARM !! WASSER !! ALARM
      message: 'Gerät: {{ trigger.to_state.name }}'
      data:
        push:
          sound:
            name: US-EN-Alexa-Water-Detected-Generic.wav
            critical: 1
            volume: 1
  mode: single
- id: '1714679978597'
  alias: Couch Schalter
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.oben_links_input_2
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    metadata: {}
    data:
      brightness_pct: 100
    target:
      entity_id: light.couch
  mode: single
