- id: '1711412922995'
  alias: Couch an
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 74a8418a735465796401d2bd7716f086
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      device_id: 558000d1060bebdc8d5fc38676f66fe4
  mode: single
- id: '1711413027657'
  alias: Couch aus
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 0dbffd293dd7591b9de64be93e01a9eb
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    target:
      device_id:
      - 558000d1060bebdc8d5fc38676f66fe4
    data: {}
  mode: single
- id: '1711413112673'
  alias: Esstisch an
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 14cd00ec73898d8d70c5ee0d583df262
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_on
    metadata: {}
    data:
      brightness_pct: 100
    target:
      device_id:
      - 97fb520e3a1d7f56f58ef4fa9b75be78
      - 598e57a4af1a721aad809e6f2e7a6bfc
      - 1b423294bef3cdefdfc43c2be192a187
      - 48519bf058c8fdc548b56a304f2a5878
      - deb3202dcf6a315e22b14211a88906d4
      - 78f0ff4058312a3a8788941a9164499b
  mode: single
- id: '1711413130920'
  alias: Esstisch aus
  description: ''
  trigger:
  - type: powered
    platform: device
    device_id: ad8b25fb9c8bca94154111c6bf4f001e
    entity_id: 7dbd6355ef1837d2cd7ce0895f90cbc4
    domain: binary_sensor
  condition: []
  action:
  - service: light.turn_off
    target:
      device_id:
      - 97fb520e3a1d7f56f58ef4fa9b75be78
      - 598e57a4af1a721aad809e6f2e7a6bfc
      - 1b423294bef3cdefdfc43c2be192a187
      - 48519bf058c8fdc548b56a304f2a5878
      - deb3202dcf6a315e22b14211a88906d4
      - 78f0ff4058312a3a8788941a9164499b
    data: {}
  mode: single
- id: '1711624301117'
  alias: Away Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.7e_20_13_94_32_d5
    from: home
    to: not_home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are not Home anymore
  - service: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id:
      - light.couch
      - light.eingang
      - light.esstisch
  mode: single
- id: '1711624343409'
  alias: Home Detector
  description: ''
  trigger:
  - platform: state
    entity_id:
    - device_tracker.7e_20_13_94_32_d5
    from: not_home
    to: home
  condition: []
  action:
  - service: notify.notify
    metadata: {}
    data:
      message: You are back Home
  mode: single
